# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20171226_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='last_updated',
            new_name='last_update',
        ),
    ]
